spring:
  application:
    name: task-manager
  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      url: ${REDIS_URL:redis://default:iZuiYNhJqvQGkXnnhABAqQtzUcUZQRuJ@trolley.proxy.rlwy.net:22881}
  cache:
    type: redis
    redis:
      time-to-live: 60000

server:
  port: 8080

logging:
  level:
    root: INFO
    com.luis.taskmanager: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
